server:
  port: 8083
service-low:
  url: "http://localhost:8081"
service-medium:
  url: "http://localhost:8082"
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 30000
