apiVersion: v1
kind: ConfigMap
metadata:
  name: service-a-config
  namespace: argoapps
data:
  application.yml: |-
    server:
      port: 8081
    spring:
      application:
        name: a
    web-client:
      service-b:
        base-url: "http://argoapps-app-b.argoapps.svc:8082"
      service-c:
        base-url: "http://argoapps-app-c.argoapps.svc:8083"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-b-config
  namespace: argoapps
data:
  application.yml: |-
    server:
      port: 8082
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-c-config
  namespace: argoapps
data:
  application.yml: |-
    server:
      port: 8083
    web-client:
      service-d:
        base-url: "http://argoapps-app-d.argoapps.svc:8084"
      service-e:
        base-url: "http://argoapps-app-e.argoapps.svc:8085"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-d-config
  namespace: argoapps
data:
  application.yml: |-
    server:
      port: 8084
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-e-config
  namespace: argoapps
data:
  application.yml: |-
    server:
      port: 8085