kind: Deployment
apiVersion: apps/v1
metadata:
  name: d
  namespace: argoapps
  labels:
    app: app-d
    app.kubernetes.io/name: app-d
    app.kubernetes.io/version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-d
  template:
    metadata:
      labels:
        app: app-d
        app.kubernetes.io/name: app-d
        app.kubernetes.io/version: 1.0.0
#      annotations:
#        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - env:
            - name: SPRING_APPLICATION
              valueFrom:
                configMapKeyRef:
                  name: service-d-config
                  key: application.yml
          name: d
          image: 'argo-serviced:1.0.0'
          ports:
            - containerPort: 8084
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 256Mi
          volumeMounts:
            - mountPath: /deployments/config/
              name: application-config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
        - name: default-secret
      dnsPolicy: ClusterFirst
      securityContext: { }
      schedulerName: default-scheduler
      volumes:
        - name: application-config
          configMap:
            name: service-d-config
            items:
              - key: application.yml
                path: application.yml
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 120
---
kind: Service
apiVersion: v1
metadata:
  name: d
  namespace: argoapps
  labels:
    app: app-d
    app.kubernetes.io/name: app-d
    app.kubernetes.io/version: 1.0.0
spec:
  ports:
    - name: http-8084
      port: 8084
      protocol: TCP
      targetPort: 8084
    - name: http-8083
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: app-d
  type: ClusterIP
