apiVersion: apps/v1
kind: Deployment
metadata:
  name: argoapps-app-b
  namespace: argoapps
  labels:
    app.kubernetes.io/component: app-b
    app.kubernetes.io/name: argoapps-app-b
    app.kubernetes.io/part-of: argoapps
    app.kubernetes.io/version: 1.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argoapps-app-b
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argoapps-app-b
#      annotations:
#        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - env:
            - name: SPRING_APPLICATION
              valueFrom:
                configMapKeyRef:
                  name: service-b-config
                  key: application.yml
          name: argoapps-app-b
          image: 'argo-serviceb:1.1.0'
          ports:
            - containerPort: 8082
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 256Mi
          volumeMounts:
            - mountPath: /deployments/config/
              name: application-config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
#      imagePullSecrets:
#        - name: default-secret
      dnsPolicy: ClusterFirst
      securityContext: { }
      schedulerName: default-scheduler
      volumes:
        - name: application-config
          configMap:
            name: service-b-config
            items:
              - key: application.yml
                path: application.yml
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 120
---
apiVersion: v1
kind: Service
metadata:
  name: argoapps-app-b
  namespace: argoapps
  labels:
    app.kubernetes.io/component: app-b
    app.kubernetes.io/name: argoapps-app-b
    app.kubernetes.io/part-of: argoapps
    app.kubernetes.io/version: 1.1.0
spec:
  ports:
    - name: http-8082
      port: 8082
      protocol: TCP
      targetPort: 8082
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/name: argoapps-app-b
  type: ClusterIP
