apiVersion: apps/v1
kind: Deployment
metadata:
  name: argoapps-app-e
  namespace: argoapps
  labels:
#    app: app-e
#    app.kubernetes.io/component: app-e
    app.kubernetes.io/name: argoapps-app-e
    app.kubernetes.io/part-of: argoapps
    app.kubernetes.io/version: 2.0.0
    app.kubernetes.io/instance: app-e
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argoapps-app-e
  template:
    metadata:
      labels:
#        app: app-e
        app.kubernetes.io/name: argoapps-app-e
        app.kubernetes.io/part-of: argoapps
        app.kubernetes.io/version: 2.0.0
        app.kubernetes.io/instance: app-e
#      annotations:
#        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - env:
            - name: SPRING_APPLICATION
              valueFrom:
                configMapKeyRef:
                  name: service-e-config
                  key: application.yml
          name: argoapps-app-e
          image: 'argo-servicee:2.0.0'
          ports:
            - containerPort: 8085
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 256Mi
          volumeMounts:
            - mountPath: /deployments/config/
              name: application-config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
#      imagePullSecrets:
#        - name: default-secret
      dnsPolicy: ClusterFirst
      securityContext: { }
      schedulerName: default-scheduler
      volumes:
        - name: application-config
          configMap:
            name: service-e-config
            items:
              - key: application.yml
                path: application.yml
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 120
---
apiVersion: v1
kind: Service
metadata:
  name: argoapps-app-e
  namespace: argoapps
  labels:
#    app: app-e
#    app.kubernetes.io/component: app-e
    app.kubernetes.io/name: argoapps-app-e
    app.kubernetes.io/part-of: argoapps
    app.kubernetes.io/version: 2.0.0
    app.kubernetes.io/instance: app-e
spec:
  ports:
    - name: http-8083
      port: 8083
      protocol: TCP
      targetPort: 8083
    - name: http-8085
      port: 8085
      protocol: TCP
      targetPort: 8085
  selector:
    app.kubernetes.io/name: argoapps-app-e
  type: ClusterIP

